### ISSUE TITLE
Choose Runtime plugin uses invalid URL to download bundled JDK

### ISSUE THREAD

**Issue by lreeder-bw** [denis-fokin/ChooseRuntime#12]
When I select JDK jbsdk11b105_linux_x64.tar.gz from the list of runtimes, and click "Install", nothing happens in the IDE.   The following shows up in <product>/system/log/idea.log:

`2019-10-16 07:27:54,392 [ 450324]   WARN - j.bootRuntime.command.Download - Cannot download 'https://bintray.com/jetbrains/intellij-jbr/download_file?file_path=jbsdk11b105_linux_x64.tar.gz': Request failed with status code 404
java.io.IOException: Cannot download 'https://bintray.com/jetbrains/intellij-jbr/download_file?file_path=jbsdk11b105_linux_x64.tar.gz': Request failed with status code 404
   at com.intellij.util.io.HttpRequests$RequestImpl.saveToFile(HttpRequests.java:468)
   at com.intellij.util.io.RequestBuilder.lambda$saveToFile$1(RequestBuilder.java:75)
   at com.intellij.util.io.HttpRequests.doProcess(HttpRequests.java:523)
   at com.intellij.util.io.HttpRequests.process(HttpRequests.java:499)
   at com.intellij.util.io.HttpRequests.access$100(HttpRequests.java:59)
   at com.intellij.util.io.HttpRequests$RequestBuilderImpl.connect(HttpRequests.java:352)
   at com.intellij.util.io.RequestBuilder.saveToFile(RequestBuilder.java:75)
   at bootRuntime.command.Download.lambda$actionPerformed$0(Download.java:38)
   at bootRuntime.command.Command$1.run(Command.java:38)
   at com.intellij.openapi.progress.impl.CoreProgressManager$TaskRunnable.run(CoreProgressManager.java:727)
   at com.intellij.openapi.progress.impl.CoreProgressManager$5.run(CoreProgressManager.java:442)
   at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$2(CoreProgressManager.java:164)
   at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:582)
   at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:532)
   at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:87)
   at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:151)
   at com.intellij.openapi.application.impl.ApplicationImpl.lambda$null$10(ApplicationImpl.java:592)
   at com.intellij.openapi.application.impl.ApplicationImpl$1.run(ApplicationImpl.java:314)
   at java.base/java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:515)
   at java.base/java.util.concurrent.FutureTask.run(FutureTask.java:264)
   at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1128)
   at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:628)
   at java.base/java.lang.Thread.run(Thread.java:834)
Caused by: com.intellij.util.io.HttpRequests$HttpStatusException: Request failed with status code 404. Status=404, Url=https://bintray.com/jetbrains/intellij-jbr/download_file?file_path=jbsdk11b105_linux_x64.tar.gz
`

**Comment by oallauddin** [comment]
Not sure what is the difference between intellij-jbr and intellij-jdk repositories.
Looks like the url should be:
https://bintray.com/jetbrains/intellij-jdk/download_file?file_path=jbsdk11b105_linux_x64.tar.gz

Here is a list of all of the files:
https://bintray.com/jetbrains/intellij-jdk/openjdk11-linux-x64
