### ISSUE TITLE
After clicking "Choose runtime" the list is loading for a few seconds and the disappears and nothings happens.

### ISSUE THREAD

**Issue by KubaKorzen** [denis-fokin/ChooseRuntime#7]
After clicking "Choose runtime" the list is loading for few seconds and the disappears and nothings happens.

**Logs:**

```
com.intellij.diagnostic.PluginException: While loading class bootRuntime.command.CommandFactory: bootRuntime/command/CommandFactory has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0 [Plugin: com.jetbrains.ChooseRuntime]
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:185)
	at com.intellij.ide.plugins.cl.PluginClassLoader.tryLoadingClass(PluginClassLoader.java:136)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClass(PluginClassLoader.java:49)
	at java.lang.ClassLoader.loadClass(ClassLoader.java:357)
	at bootRuntime.main.Controller.<init>(Controller.kt:25)
	at bootRuntime.main.ChooseBootRuntimeAction.actionPerformed(ChooseBootRuntimeAction.kt:60)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:260)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:277)
	at com.intellij.ide.actions.GotoActionAction.lambda$performAction$7(GotoActionAction.java:351)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransactionLater$4(TransactionGuardImpl.java:271)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:747)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:696)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
Caused by: java.lang.UnsupportedClassVersionError: bootRuntime/command/CommandFactory has been compiled by a more recent version of the Java Runtime (class file version 55.0), this version of the Java Runtime only recognizes class file versions up to 52.0
	at java.lang.ClassLoader.defineClass1(Native Method)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:763)
	at java.lang.ClassLoader.defineClass(ClassLoader.java:642)
	at com.intellij.util.lang.UrlClassLoader._defineClass(UrlClassLoader.java:306)
	at com.intellij.util.lang.UrlClassLoader.defineClass(UrlClassLoader.java:302)
	at com.intellij.util.lang.UrlClassLoader._findClass(UrlClassLoader.java:271)
	at com.intellij.ide.plugins.cl.PluginClassLoader.loadClassInsideSelf(PluginClassLoader.java:182)
	... 32 more
```

**Comment by denis-fokin** [comment]
Thank you for the report! Could you give a try to the latest 1.0.4 version of the plugin?

**Comment by KubaKorzen** [comment]
Sure. After update to 1.0.4 I got another pop up for a second and then still nothing. 

Logs:
```
2019-10-02 10:59:49,481 [ 250120]  ERROR - pplication.impl.LaterInvocator - ProgressManager.getInsta…tanceEx().defaultProject) must not be null 
java.lang.IllegalStateException: ProgressManager.getInsta…tanceEx().defaultProject) must not be null
	at bootRuntime.bundles.Runtime.fetchVersion(Runtime.kt:46)
	at bootRuntime.bundles.Local$version$2.invoke(Local.kt:16)
	at bootRuntime.bundles.Local$version$2.invoke(Local.kt:10)
	at kotlin.SynchronizedLazyImpl.getValue(LazyJVM.kt:74)
	at bootRuntime.bundles.Local.getVersion(Local.kt)
	at bootRuntime.bundles.Local.toString(Local.kt:28)
	at com.intellij.ui.ComboBoxCompositeEditor$1.lambda$$0(ComboBoxCompositeEditor.java:78)
	at com.intellij.ui.ComboBoxCompositeEditor$1.setItem(ComboBoxCompositeEditor.java:83)
	at com.intellij.ui.ComboBoxCompositeEditor$3.setItem(ComboBoxCompositeEditor.java:186)
	at com.intellij.ui.ComboBoxCompositeEditor.setItem(ComboBoxCompositeEditor.java:242)
	at bootRuntime.main.ChooseBootRuntimeAction$actionPerformed$2.setItem(ChooseBootRuntimeAction.kt:107)
	at com.intellij.openapi.ui.ComboBox$MyEditor.setItem(ComboBox.java:338)
	at javax.swing.JComboBox.configureEditor(JComboBox.java:1404)
	at javax.swing.plaf.basic.BasicComboBoxUI$Handler.contentsChanged(BasicComboBoxUI.java:1864)
	at javax.swing.AbstractListModel.fireContentsChanged(AbstractListModel.java:118)
	at com.intellij.ui.CollectionComboBoxModel.update(CollectionComboBoxModel.java:66)
	at com.intellij.ui.CollectionComboBoxModel.setSelectedItem(CollectionComboBoxModel.java:50)
	at javax.swing.JComboBox.setSelectedItem(JComboBox.java:576)
	at bootRuntime.main.ChooseBootRuntimeAction.actionPerformed(ChooseBootRuntimeAction.kt:151)
	at com.intellij.openapi.actionSystem.ex.ActionUtil$1.run(ActionUtil.java:260)
	at com.intellij.openapi.actionSystem.ex.ActionUtil.performActionDumbAware(ActionUtil.java:277)
	at com.intellij.ide.actions.GotoActionAction.lambda$performAction$7(GotoActionAction.java:351)
	at com.intellij.openapi.application.TransactionGuardImpl.runSyncTransaction(TransactionGuardImpl.java:88)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransaction$1(TransactionGuardImpl.java:111)
	at com.intellij.openapi.application.TransactionGuardImpl.submitTransaction(TransactionGuardImpl.java:120)
	at com.intellij.openapi.application.TransactionGuardImpl.lambda$submitTransactionLater$4(TransactionGuardImpl.java:271)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.doRun(LaterInvocator.java:435)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.runNextEvent(LaterInvocator.java:419)
	at com.intellij.openapi.application.impl.LaterInvocator$FlushQueue.run(LaterInvocator.java:403)
	at java.awt.event.InvocationEvent.dispatch(InvocationEvent.java:311)
	at java.awt.EventQueue.dispatchEventImpl(EventQueue.java:758)
	at java.awt.EventQueue.access$500(EventQueue.java:97)
	at java.awt.EventQueue$3.run(EventQueue.java:709)
	at java.awt.EventQueue$3.run(EventQueue.java:703)
	at java.security.AccessController.doPrivileged(Native Method)
	at java.security.ProtectionDomain$JavaSecurityAccessImpl.doIntersectionPrivilege(ProtectionDomain.java:74)
	at java.awt.EventQueue.dispatchEvent(EventQueue.java:728)
	at com.intellij.ide.IdeEventQueue.defaultDispatchEvent(IdeEventQueue.java:747)
	at com.intellij.ide.IdeEventQueue._dispatchEvent(IdeEventQueue.java:696)
	at com.intellij.ide.IdeEventQueue.dispatchEvent(IdeEventQueue.java:391)
	at java.awt.EventDispatchThread.pumpOneEventForFilters(EventDispatchThread.java:205)
	at java.awt.EventDispatchThread.pumpEventsForFilter(EventDispatchThread.java:116)
	at java.awt.EventDispatchThread.pumpEventsForHierarchy(EventDispatchThread.java:105)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:101)
	at java.awt.EventDispatchThread.pumpEvents(EventDispatchThread.java:93)
	at java.awt.EventDispatchThread.run(EventDispatchThread.java:82)
```

**Comment by denis-fokin** [comment]
Could you paste the IDE About information here?

**Comment by denis-fokin** [comment]
Could you give another try to version 1.0.7?
